### ISSUE TITLE
software installation

### ISSUE THREAD

**Issue by daler** [kundajelab/TF_chipseq_pipeline#1]
[bioconda](https://bioconda.github.io/) might help make the software installation much faster and reproducible. For example if you write a `requirements.txt` that looks something like:

```
bwa ==0.7.3
samtools ==0.1.19
bedtools ==2.19
ucsc-wigtobigwig
ucsc-bedgraphtobigwig
ucsc-bigwiginfo
ucsc-bedclip
matplotlib
numpy
scipy
# ...and everything else you need
```

Then everything can be installed with:

```bash
conda install \
--prefix $SOFTWARE_HOME/software_bds \
--file requirements.txt \
--channel bioconda
```

A couple details: 
- it looks like in `install_dependencies.sh` you manually separate Python environments, which can also be handled by conda. You would need a second requirements file and would need to choose a different directory
- there are a couple of tools not yet on bioconda, but that's an easy fix. Exception to that might be MCR due to licensing
- `--prefix $HOME/software_bds` in the conda command creates the environment there, minimizing changes to the pipeline

Just a suggestion. I used to have installation scripts like this but then found conda. Then bioconda came along and helped more. Made things much easier for other people to get things running and much less brittle.

**Comment by leepc12** [comment]
I appreciate your advice. This was what I have been looking for. I will
update the installer with it in the next release.

Thanks!

Jin

**Comment by leepc12** [comment]
AQUAS pipeline now supports anaconda virtual environment. You don't have to add those parameters if you have installed dependencies with `install_dependencies.sh`.

bds chipseq.bds -conda_env [CONDA_ENV_PY2] -conda_env [CONDA_ENV_PY3]

However, some R packages (snowfall, spp, ...) in R 2.15.x, Anshul's software (phantompeakqualtools and align2rawsignal) and MCR were not available in official conda channels. So you still need to install them with an updated install_dependencies.sh.

**Comment by daler** [comment]
Very nice, thanks.

Just FYI, `spp` is available in the [bioconda](https://bioconda.github.io/) channel as well as some other  R packages. I'd be happy to help get recipes for the other dependencies added as well if you're interested.

**Comment by akundaje** [comment]
I don't think the latest version of SPP is on there. It (SPP) was updated
just a few months ago with changes we specifically added.

Anshul

**Comment by akundaje** [comment]
It would be really great if you would help with missing dependencies.

Anshul

**Comment by akundaje** [comment]
The latest version of SPP is here https://github.com/hms-dbmi/spp

**Comment by daler** [comment]
Ah great, I missed that SPP is on github now. Good to know. I will look into getting the dependencies sorted out.
